---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2a
spec:
  securityGroups: 
    - sg-08673cba2b1bef174
  subnet: subnet-05f46a6cf13616ef5
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2c
spec:
  securityGroups: 
    - sg-08673cba2b1bef174
  subnet: subnet-0c443666a360fd1bb